[package]
name    = "vault_router"
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "20"
shared = { path = "../shared" }

[dev-dependencies]
soroban-sdk = { version = "20", features = ["testutils"] }
shared = { path = "../shared", features = ["testutils"] }
vault_l3 = { path = "../vault_l3" }
vault_l6 = { path = "../vault_l6" }
vault_l12 = { path = "../vault_l12" }
vault_flex = { path = "../vault_flex" }